---
title: catchError
---

<Callout>
New in v1.7.0
</Callout>

```tsx
import { catchError } from "solid-js"

function catchError<T>(tryFn: () => T, onError: (err: any) => void): T
```

Wraps a `tryFn` with an error handler that fires if an error occurs below that point. 
Only the nearest scope error handlers execute. 
Rethrow to trigger up the line.